services:
  master:
    build: .
    ports:
      - "8089:8089"
      - "5557:5557"
    volumes:
      - ./:/mnt/locust
    env_file:
      - .env
    command: -f /mnt/locust/locustfile.py --master -H $TARGET_API_SERVER

  worker:
    build: .
    volumes:
      - ./:/mnt/locust
    env_file:
      - .env
    command: -f /mnt/locust/locustfile.py --worker --master-host master
